### ISSUE TITLE
Updating to Babel 6.0

### ISSUE THREAD

**Issue by TimothyGu** [jstransformers/jstransformer-babel#18]
Babel 6.0.0 brought [a lot of changes](https://babeljs.io/blog/2015/10/29/6.0.0/). Therefore, we now need to make sure the presets, etc. work with the jstransformer architecture. And, I plan to release a 1.0.0 first for Babel 5, and 2.0.0 for Babel 6.

**Comment by RobLoach** [comment]
:+1:

**Comment by TimothyGu** [comment]
jstransformer-babel@1.0.1 tagged and published.

v6 branch [created](https://github.com/jstransformers/jstransformer-babel/compare/v6) and implemented.

Pending on jstransformers/jstransformer#130 which will make 6238ea5f2d33916fa7ccb9295c43506fde79fc2b true, and `.babelrc` a lot easier to use.
